In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import random
from pprint import pprint

In [ ]:
data =  pd.read_csv('/kaggle/input/training-data/train.csv')

In [ ]:
data = data.drop('TransactionID', axis=1)

In [10]:
data.head()

,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,TransactionDT,...,C6,C7,C8,C9,C10,C11,C12,C13,C14,isFraud
0,C,5812,408.0,185.0,mastercard,224.0,debit,NotFound,NotFound,11844610,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
1,W,12577,268.0,150.0,visa,166.0,debit,123.0,87.0,12274010,...,94.0,0.0,0.0,85.0,0.0,104.0,0.0,457.0,120.0,0
2,H,12581,453.0,150.0,visa,226.0,debit,272.0,87.0,1343827,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0
3,W,8139,327.0,150.0,discover,194.0,credit,204.0,87.0,15034938,...,2.0,0.0,0.0,2.0,0.0,3.0,0.0,18.0,6.0,0
4,W,16132,111.0,150.0,visa,226.0,debit,220.0,87.0,14680707,...,2.0,0.0,0.0,1.0,0.0,1.0,0.0,28.0,1.0,0

In [18]:
df = data.values

In [59]:
df[:5]

array([['C', 5812, '408.0', '185.0', 'mastercard', '224.0', 'debit',
        'NotFound', 'NotFound', 11844610, 22.14, 1.0, 1.0, 0.0, 1.0, 0.0,
        1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0],
       ['W', 12577, '268.0', '150.0', 'visa', '166.0', 'debit', '123.0',
        '87.0', 12274010, 107.94, 141.0, 124.0, 0.0, 0.0, 123.0, 94.0,
        0.0, 0.0, 85.0, 0.0, 104.0, 0.0, 457.0, 120.0, 0],
       ['H', 12581, '453.0', '150.0', 'visa', '226.0', 'debit', '272.0',
        '87.0', 1343827, 75.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0],
       ['W', 8139, '327.0', '150.0', 'discover', '194.0', 'credit',
        '204.0', '87.0', 15034938, 92.0, 6.0, 1.0, 0.0, 0.0, 0.0, 2.0,
        0.0, 0.0, 2.0, 0.0, 3.0, 0.0, 18.0, 6.0, 0],
       ['W', 16132, '111.0', '150.0', 'visa', '226.0', 'debit', '220.0',
        '87.0', 14680707, 39.0, 1.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0,
        1.0, 0.0, 1.0, 0.0, 28.0, 1.0, 0]], dtype=object)

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>

RangeIndex: 472432 entries, 0 to 472431

Data columns (total 26 columns):

 #   Column          Non-Null Count   Dtype

---  ------          --------------   -----

 0   ProductCD       472432 non-null  object

 1   card1           472432 non-null  int64

 2   card2           472432 non-null  object

 3   card3           472432 non-null  object

 4   card4           472432 non-null  object

 5   card5           472432 non-null  object

 6   card6           472432 non-null  object

 7   addr1           472432 non-null  object

 8   addr2           472432 non-null  object

 9   TransactionDT   472432 non-null  int64

 10  TransactionAmt  472432 non-null  float64

 11  C1              472432 non-null  float64

 12  C2              472432 non-null  float64

 13  C3              472432 non-null  float64

 14  C4              472432 non-null  float64

 15  C5              472432 non-null  float64

 16  C6              472432 non-null  float64

 17  C7              472432 non-null  float64

 18  C8              472432 non-null  float64

 19  C9              472432 non-null  float64

 20  C10             472432 non-null  float64

 21  C11             472432 non-null  float64

 22  C12             472432 non-null  float64

 23  C13             472432 non-null  float64

 24  C14             472432 non-null  float64

 25  isFraud         472432 non-null  int64

dtypes: float64(15), int64(3), object(8)

memory usage: 93.7+ MB

In [11]:
def purity(data):
    target_column = data[:, -1]
    unique_classes = np.unique(target_column)
    if len(unique_classes)==1:
        return True
    else:
        return False

In [12]:
def classify_data(data):
    target_column = data
    unique_classes, classes_counts = np.unique(target_column, return_counts = True)
    print(classes_counts)
    index = classes_counts.argmax()
    classification = unique_classes[index]
    
    return classification

In [13]:
classify_data(data['isFraud'].values)

[455902  16530]

0

In [ ]:
#def get_potential_splits(data):
    
    
   # return potential_splits

In [108]:
data.shape

(472432, 27)

In [109]:
#handling missing data

In [14]:
b = pd.DataFrame(data)
b['card1'] = b['card1'].replace('NotFound', 0 )
b['card2'] = b['card2'].replace('NotFound', 0 )
b['card3'] = b['card3'].replace('NotFound', 0 )
b['card5'] = b['card5'].replace('NotFound', 0 )
b['addr1'] = b['addr1'].replace('NotFound', 0 )
b['addr2'] = b['addr2'].replace('NotFound', 0 )

median_card1 = b.card1.median()
median_card2 = b.card2.median()
mode_card3 = b.card3.mode()
mode_card4 = b.card4.mode()
median_card5 = b.card5.median()
mode_card6 = b.card6.mode()
mode_addr1 = b.addr1.mode()
mode_addr2 = b.addr2.mode()

print(median_card1)
print(mode_card3)
print(mode_card4)
print(mode_card6)

9680.0
0    150.0
Name: card3, dtype: object
0    visa
Name: card4, dtype: object
0    debit
Name: card6, dtype: object

In [15]:
b['card1'] = b['card1'].fillna({0: median_card1})
b['card2'] = b['card2'].fillna({0: median_card2})
b['card3'] = b['card3'].fillna({0: mode_card3})
b['card4'] = b['card4'].fillna({'NotFound': str(mode_card4)})
b['card5'] = b['card5'].fillna({0: median_card5})
b['card6'] = b['card6'].fillna({'NotFound': str(mode_card6)})
b['addr1'] = b['addr1'].fillna({0: mode_addr1})
b['addr2'] = b['addr2'].fillna({0: mode_addr2})

In [16]:
b.head()

,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,TransactionDT,...,C6,C7,C8,C9,C10,C11,C12,C13,C14,isFraud
0,C,5812,408.0,185.0,mastercard,224.0,debit,0,0,11844610,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
1,W,12577,268.0,150.0,visa,166.0,debit,123.0,87.0,12274010,...,94.0,0.0,0.0,85.0,0.0,104.0,0.0,457.0,120.0,0
2,H,12581,453.0,150.0,visa,226.0,debit,272.0,87.0,1343827,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0
3,W,8139,327.0,150.0,discover,194.0,credit,204.0,87.0,15034938,...,2.0,0.0,0.0,2.0,0.0,3.0,0.0,18.0,6.0,0
4,W,16132,111.0,150.0,visa,226.0,debit,220.0,87.0,14680707,...,2.0,0.0,0.0,1.0,0.0,1.0,0.0,28.0,1.0,0

In [17]:
for i in b.columns:
    print(i , '-', len(b[i].unique()))

ProductCD - 5
card1 - 12815
card2 - 501
card3 - 112
card4 - 5
card5 - 115
card6 - 5
addr1 - 304
addr2 - 72
TransactionDT - 461340
TransactionAmt - 7898
C1 - 1350
C2 - 1064
C3 - 21
C4 - 1078
C5 - 319
C6 - 1158
C7 - 914
C8 - 1002
C9 - 204
C10 - 987
C11 - 1210
C12 - 927
C13 - 1393
C14 - 1018
isFraud - 2

In [49]:
b.head()

,TransactionID,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,...,C6,C7,C8,C9,C10,C11,C12,C13,C14,isFraud
0,1,C,5812,408.0,185.0,mastercard,224.0,debit,0,0,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
1,2,W,12577,268.0,150.0,visa,166.0,debit,123.0,87.0,...,94.0,0.0,0.0,85.0,0.0,104.0,0.0,457.0,120.0,0
2,3,H,12581,453.0,150.0,visa,226.0,debit,272.0,87.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0
3,4,W,8139,327.0,150.0,discover,194.0,credit,204.0,87.0,...,2.0,0.0,0.0,2.0,0.0,3.0,0.0,18.0,6.0,0
4,5,W,16132,111.0,150.0,visa,226.0,debit,220.0,87.0,...,2.0,0.0,0.0,1.0,0.0,1.0,0.0,28.0,1.0,0

In [18]:
for i in b.columns:
    print(i , '-', len(b[i].unique()))

ProductCD - 5
card1 - 12815
card2 - 501
card3 - 112
card4 - 5
card5 - 115
card6 - 5
addr1 - 304
addr2 - 72
TransactionDT - 461340
TransactionAmt - 7898
C1 - 1350
C2 - 1064
C3 - 21
C4 - 1078
C5 - 319
C6 - 1158
C7 - 914
C8 - 1002
C9 - 204
C10 - 987
C11 - 1210
C12 - 927
C13 - 1393
C14 - 1018
isFraud - 2

In [7]:
def det_feature_type(data):
    featuretypes = []
    x_unique_values_thresh = 15
    
    for column in b.columns:
        uniquevals = b[column].unique()
        exval = uniquevals[0]
        
        if (len(uniquevals)<=x_unique_values_thresh):
            featuretypes.append('categorical')
        else:
            featuretypes.append('continuous')
            
            
    return featuretypes

In [20]:
column_data_types = det_feature_type(b)
i=0
for column in b.columns:
    print(column , '-', column_data_types[i])
    i += 1

ProductCD - categorical
card1 - continuous
card2 - continuous
card3 - continuous
card4 - categorical
card5 - continuous
card6 - categorical
addr1 - continuous
addr2 - continuous
TransactionDT - continuous
TransactionAmt - continuous
C1 - continuous
C2 - continuous
C3 - continuous
C4 - continuous
C5 - continuous
C6 - continuous
C7 - continuous
C8 - continuous
C9 - continuous
C10 - continuous
C11 - continuous
C12 - continuous
C13 - continuous
C14 - continuous
isFraud - categorical

In [60]:
### splits

In [2]:
def split_data(df, split_column, split_value):
    
    splitcolumnvalues = df[:, split_column]
    
    type_of_feature = FEATURE_TYPES[split_column] 
    
    if type_of_feature == 'continuous':
        databelow = df[splitcolumnvalues <= split_value]
        dataabove = df[splitcolumnvalues > split_value]
    else:
        for i in unique(data[split_column].values):
            print(f"data_{i}") = data[split_column == i]
    return databelow, dataabove, data_{i}

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (2258136923.py, line 12)

In [6]:
#nd = data.values

In [29]:

#split_value = np.mean(df[:, split_column])
split_value = round(np.mean(df[:,2]))
databelow, dataabove = split_data(df, split_column, split_value)
print(databelow)
print(dataabove)

[[1 'C' 5812 ... 1.0 1.0 0]
 [4 'W' 8139 ... 18.0 6.0 0]
 [8 'W' 5606 ... 13.0 1.0 0]
 ...
 [472430 'W' 8868 ... 1.0 1.0 0]
 [472431 'W' 8320 ... 1.0 1.0 0]
 [472432 'H' 6019 ... 1.0 1.0 0]]
[[2 'W' 12577 ... 457.0 120.0 0]
 [3 'H' 12581 ... 1.0 1.0 0]
 [5 'W' 16132 ... 28.0 1.0 0]
 ...
 [472423 'W' 13139 ... 2.0 2.0 0]
 [472424 'W' 12577 ... 423.0 100.0 0]
 [472425 'C' 12730 ... 1.0 1.0 0]]

In [15]:
#for values in nd[:, 3]:
   # if isinstance(values, str):
       # int(values)
   # else: exit()

In [ ]:
print(len(databelow))
print(len(dataabove))

In [ ]:
#calculating entropy

In [52]:
def calculate_entropy(df, target_column_index):
    target_column = df[:, target_column_index]
    _, counts = np.unique(target_column, return_counts = True)
    probabilities = counts/counts.sum()
    
    entropy = sum(probabilities*-np.log2(probabilities))
    
    return entropy

In [53]:
calculate_entropy(df, 0)

18.84974716293102

In [33]:
print(databelow)

[[1 'C' 5812 ... 1.0 1.0 0]
 [4 'W' 8139 ... 18.0 6.0 0]
 [8 'W' 5606 ... 13.0 1.0 0]
 ...
 [472430 'W' 8868 ... 1.0 1.0 0]
 [472431 'W' 8320 ... 1.0 1.0 0]
 [472432 'H' 6019 ... 1.0 1.0 0]]

In [54]:
def calc_information_gain(target_column, databelow, dataabove):
    
    information_gain = calculate_entropy(target_column) - calculate_entropy(databelow) - calculate_entropy(dataabove)
    
    return information_gain

In [55]:
def select_best_feature(data):
    for column in data.columns:
        IGlist = calc_information_gain(column)
        
    return data[max(IGlist)]

In [ ]:
def chi_square_test (target_column, split_data):
    real = []
    divisions, counts = target_column.unique()

In [3]:
def calculate_chi_square(observed, expected):
    return np.sum((observed - expected)**2 / expected)


def chi_square_test(target_column, target):

    uniquevals = np.unique(target_column)
    chi_square_values = []

    for value in uniquevals:
    
        value_samples = target_column == value
        positive_samples = target[value_samples]
        negative_samples = target[~value_samples]
        real = np.array([[np.sum(positive_samples), np.sum(negative_samples)]])
        
        totalsample = len(target_column)
        totalpositive = np.sum(target)
        totalnegative = totalsample-totalpositive
        total_value_sample = np.sum(value_samples)
    
        expected_positive = total_value_sample*(totalpositive/totalsample)
        expected_negative = total_value_sample*(totalnegative/totalsample)
        expected = np.array([[expected_positive, expected_negative]])
    
        chi_square_value = calculate_chi_square(observed, expected)
        chi_square_values.append(chi_square_value)
    
    return np.max(chi_square_values)

In [6]:
def decision_tree(data, counter = 0):
    
    if counter == 0:
        global COLUMN_HEADERS, FEATURE_TYPES
        COLUMN_HEADERS = data.columns
        FEATURE_TYPES = det_feature_type(data)
        treedata = data.values 
    else:
        treedata = data
    
    #base case
    for i in data.columns:
        if len(unique(data.columns)) == 1:
            print('data pure')
            
        else:
            print('data unpure')
            counter += 1
            
            #helper functions
            target_column = i in range(df.columns)
            calculate_entropy(df, target_column_index)
            calc_information_gain(target_column, databelow, dataabove)